### ISSUE TITLE
Error: Private key must be greater than 0 and Error: Bad Request

### ISSUE THREAD

**Issue by VishalDalve** [Blank101/bitcoin-transaction#11]
Working on mainnet, getting these two issues.
Creating WIF From Node Module :

 ```
var wif = require('wif');
var privateKey = new Buffer('btc_private_key', 'hex');
var key = wif.encode(128, privateKey, true)
console.log("WIF key",key);
```

What i'm doing wrong?

```
bitcoinTransaction.getBalance(from, { network: "mainnet" }).then((balanceInBTC) => {
	return bitcoinTransaction.sendTransaction({
		from: from,
		to: to,
		privKeyWIF: key,
		btc: 0.0002,
		fee:"hour",
		network: "mainnet"
	});
}).then((res) => {
	console.log(res.body);
	console.log("---------------------------------------------------------");
	console.log("Hash: ",res.body.tx.hash);
});
```

**Comment by hexonaut** [comment]
Is your private key of the form that looks like this? `cNZi8iySqBToXMpcsQaHKD5uv7HExBQJBSi4dTg3ZPaEzeNAzvbj`

**Comment by VishalDalve** [comment]
> Is your private key of the form that looks like this? `cNZi8iySqBToXMpcsQaHKD5uv7HExBQJBSi4dTg3ZPaEzeNAzvbj`

My Private key : KxdaerRrP1fcrxxxxxxgGgXMvxXXX3A4u3jxHxxxxxxHuPc5yNNg (kind of, 52 char).

**Comment by VishalDalve** [comment]
Now able to send value (But only whole amount present on address, not specific ),Also Not getting HASH of transaction on mainnet.i.e Empty response. Thanks.
