### ISSUE TITLE
You do not have enough in your wallet to send that much.

### ISSUE THREAD

**Issue by Abhishekoodles1** [Blank101/bitcoin-transaction#15]
I have created one cold wallet in which have balance 0.0015, the address is " 38SXigeP4z7KyPEcjT697vWWkr9LnSsseS"  but when I am trying to transfer 0.001 amount using its private key to some other destination address, it is giving me error like "You do not have enough in your wallet to send that much"?

**Comment by hexonaut** [comment]
It's possible the fees being calculated are putting you over the limit. Try setting the fee argument to "hour" instead of the default "fastest". If that is still not working then maybe try topping up the account slightly or reduce the amount you are sending.

**Comment by Abhishekoodles1** [comment]
Thanks for your suggestion, I will try to increase the balance in my wallet and then check again. I also want to know that can I send the complete balance at one time and the fee be will automatically deducted?

**Comment by Abhishekoodles1** [comment]
Also when i changed fee argument to "hour" ,I  am getting error " Error: Internal Server Error" ?

**Comment by hexonaut** [comment]
> Thanks for your suggestion, I will try to increase the balance in my wallet and then check again. I also want to know that can I send the complete balance at one time and the fee be will automatically deducted?

Automatic calculation of that is not currently available, but could make for a useful addition. I opened an issue #16

> Also when i changed fee argument to "hour" ,I am getting error " Error: Internal Server Error" ?

Not sure about this. Can you open an issue and provide more details?
