### ISSUE TITLE
You do not have enough in your wallet to send that much.

### ISSUE THREAD

**Issue by borutkitak** [Blank101/bitcoin-transaction#6]
Hello. I want to use your library in my project but sometimes I get error "You do not have enough in your wallet to send that much." but I have enough funds. This happens from time to time. Any ideas?

Thanks

**Comment by kemalmustafic** [comment]
Same happens here

**Comment by hexonaut** [comment]
Did you just receive funds into the account you are transferring out of? Every incoming transaction must have at least 6 confirmations before it is counted as available to transfer out. This can take 10s of minutes.

**Comment by borutkitak** [comment]
Yes that was it, I just figure it out few days ago. Thank you

**Comment by hexonaut** [comment]
No problem.

**Comment by Stefanats** [comment]
Hello. I am using copay wallet app and i have funds on it, but every time its shows me 0.
![screenshot from 2018-08-15 16-13-01](https://user-images.githubusercontent.com/33752425/44152545-1efa329c-a0a6-11e8-9d79-180d08e07c62.png)

**Comment by hexonaut** [comment]
That code returns the wallet amount for the address in the `from` variable on the testnet. You have to remove the `{ network: "testnet" }` and set the `from` address to be your own wallet address to get your wallet's amount.

**Comment by Stefanats** [comment]
Im using testnet wallet, also in the 'from' i set my test address, so i need that code line.

**Comment by hexonaut** [comment]
The from address in your screenshot is the address from the example on the README. If you changed it after the screenshot then perhaps try double checking you have coins in a block explorer.

**Comment by Stefanats** [comment]
I was using my own address after screenshot, also i have coins.
![screenshot from 2018-08-20 10-04-58](https://user-images.githubusercontent.com/33752425/44328006-afea8c80-a460-11e8-8931-0dfb1a167144.png)
![image1](https://user-images.githubusercontent.com/33752425/44328015-b547d700-a460-11e8-9cd2-3cf01eb80a7b.png)
