### ISSUE TITLE
Number of confirmations is fixed

### ISSUE THREAD

**Issue by osagga** [Blank101/bitcoin-transaction#8]
https://github.com/Blank101/bitcoin-transaction/blob/a60bc3f201601d0d80b9e2af68ba189db4e2b077/index.js#L190

The number of confirmations should be controllable, at least for `testnet`.

**Comment by hexonaut** [comment]
Yes this is a good point. I can make this change when I get a moment (or feel free to submit a PR, and I'll merge it in right away). :)

**Comment by kidsil** [comment]
just noticed @osagga  's PR after adding my own: https://github.com/Blank101/bitcoin-transaction/pull/10
Mine doesn't have the indentation fixes so it's more concentrated on the feature :)

**Comment by hexonaut** [comment]
@kidsil Merged yours in.
